"""add_user_id_to_trades_table

Revision ID: 1528c746009a
Revises: e537fa9ca901
Create Date: 2025-07-30 11:00:52.687758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1528c746009a'
down_revision: Union[str, Sequence[str], None] = 'e537fa9ca901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trades', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'user_id')
    # ### end Alembic commands ###
