"""add_name_column_and_make_mobile_required

Revision ID: 1ef0dba37c32
Revises: c1ca412f0967
Create Date: 2025-07-31 10:40:14.821190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef0dba37c32'
down_revision: Union[str, Sequence[str], None] = 'c1ca412f0967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    
    # Update existing users with names extracted from emails
    connection = op.get_bind()
    users = connection.execute(sa.text("SELECT id, email FROM users WHERE name IS NULL"))
    
    for user in users:
        # Extract name from email (part before @)
        email = user[1]
        name_part = email.split('@')[0]
        # Replace common separators with spaces and capitalize
        import re
        name_part = re.sub(r'[._-]', ' ', name_part)
        name_part = ' '.join(word.capitalize() for word in name_part.split())
        
        connection.execute(
            sa.text("UPDATE users SET name = :name WHERE id = :id"),
            {"name": name_part, "id": user[0]}
        )
    
    # Now make the column not null
    op.alter_column('users', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
