"""Add missing columns to users table

Revision ID: 3cef425295e7
Revises: ae1383a808b0
Create Date: 2025-07-29 12:10:48.384528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cef425295e7'
down_revision: Union[str, Sequence[str], None] = 'ae1383a808b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('broker_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'broker_refresh_token')
    # ### end Alembic commands ###
