"""make_mobile_required

Revision ID: a8abc5fc5cdf
Revises: 1ef0dba37c32
Create Date: 2025-07-31 10:49:53.697076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8abc5fc5cdf'
down_revision: Union[str, Sequence[str], None] = '1ef0dba37c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First update existing users with null mobile to have a default value
    connection = op.get_bind()
    connection.execute(
        sa.text("UPDATE users SET mobile = '0000000000' WHERE mobile IS NULL")
    )
    
    # Now make the column not null
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
