"""add_capital_column_to_users

Revision ID: aa511d8b66c2
Revises: a8abc5fc5cdf
Create Date: 2025-07-31 12:27:35.266013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa511d8b66c2'
down_revision: Union[str, Sequence[str], None] = 'a8abc5fc5cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('users', sa.Column('capital', sa.Integer(), nullable=True))
    
    # Update existing records with default value
    op.execute("UPDATE users SET capital = 0 WHERE capital IS NULL")
    
    # Make the column not nullable
    op.alter_column('users', 'capital', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'capital')
    # ### end Alembic commands ###
