"""update_audit_model_with_complete_log_fields

Revision ID: aafab7ef4dc0
Revises: 1528c746009a
Create Date: 2025-07-30 11:24:49.180890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafab7ef4dc0'
down_revision: Union[str, Sequence[str], None] = '1528c746009a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('level', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('user_email', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('correlation_id', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('context', sa.JSON(), nullable=True))
    op.add_column('audit', sa.Column('method', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('url', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('client_ip', sa.String(), nullable=True))
    op.add_column('audit', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('audit', sa.Column('stack_trace', sa.Text(), nullable=True))
    op.add_column('audit', sa.Column('request_data', sa.JSON(), nullable=True))
    op.add_column('audit', sa.Column('response_data', sa.JSON(), nullable=True))
    op.add_column('audit', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('audit', sa.Column('status_code', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'status_code')
    op.drop_column('audit', 'duration_ms')
    op.drop_column('audit', 'response_data')
    op.drop_column('audit', 'request_data')
    op.drop_column('audit', 'stack_trace')
    op.drop_column('audit', 'error_message')
    op.drop_column('audit', 'client_ip')
    op.drop_column('audit', 'url')
    op.drop_column('audit', 'method')
    op.drop_column('audit', 'context')
    op.drop_column('audit', 'correlation_id')
    op.drop_column('audit', 'user_email')
    op.drop_column('audit', 'user_id')
    op.drop_column('audit', 'level')
    # ### end Alembic commands ###
