"""add_order_executed_at_and_update_datetime_fields

Revision ID: e537fa9ca901
Revises: ec8d5c13e898
Create Date: 2025-07-30 10:51:10.471446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e537fa9ca901'
down_revision: Union[str, Sequence[str], None] = 'ec8d5c13e898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_executed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_executed_at')
    # ### end Alembic commands ###
