"""Add order relationship to trades table

Revision ID: ec8d5c13e898
Revises: 3cef425295e7
Create Date: 2025-07-29 12:35:11.670106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8d5c13e898'
down_revision: Union[str, Sequence[str], None] = '3cef425295e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trades', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'order_id')
    # ### end Alembic commands ###
